In [12]:
import numpy as np

a=np.array([1,2,3,4])                                                           #creating an 1D array
t=np.array([[1,2,3],[4,5,6]])                                                   #creating an 2D array
u=np.array([[[1,2,3],[4,5,6],[7,8,9]]])                                         #creating an 3D array
print(a)
print(type(a))                                                                  #checking data type

c=np.zeros((2,3))                                                              #Zeroes() function
d=np.ones((3,4))                                                                #Ones() function

e=np.arange(0,10,2)                                                             #creating an array using .arange() function
f=np.linspace(0,10,5)                                                           #creating an array using .linspace() function
print("\n")

g=np.array([[1,2,3],[4,5,6]])
print(g.shape)                                                                  #array properties using .shape command
print(g.ndim)                                                                   #array properties using .ndim command
print(g.dtype)                                                                  #array properties using .dtype command
print("\n")


h=np.array([[1,2,3,4],[5,6,7,8]])
print(h[1:])                                                                    #Indexing & Slicing of an array
print(h[1,2])
print(h[0,1:])
print("\n")


i=np.arange(1,13)
print(i)
j=i.reshape(3,4)                                                                #Reshaping an array
print(j)
print("\n")

k=np.arange(1,13)
l=k.reshape(3,4)
m=l.flatten()                                                                   # .flatten() function
n=l.ravel()                                                                     # .ravel() function
print(m)
print("\n")
print(n)
print("\n")

o=np.array([1,2,3,8,12,19])
print(o>5)                                                                      #Boolean Masking
print(o[0>5])

p=np.array([1,2,3,4,5])                                                         #Vectorised Operations
p=p+2
print(p)
p=p*2
print(p)

q=np.array([[1,2,3],[4,5,6]])                                                   #Broadcasting concept
r=np.array([10,20,30])
print(q+r)
print("\n")

s=np.array([1,2,3,4,5,6,7,8])                                                   #Aggregate Functions
print("Sum: ", np.sum(s))
print("Minimum: ", np.min(s))
print("Maximum: ", np.max(s))
print("Mean: ", np.max(s))
print("Standard Deviation: ", np.std(s))



[1 2 3 4]
<class 'numpy.ndarray'>


(2, 3)
2
int64


[[5 6 7 8]]
7
[2 3 4]


[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


[ 1  2  3  4  5  6  7  8  9 10 11 12]


[ 1  2  3  4  5  6  7  8  9 10 11 12]


[False False False  True  True  True]
[]
[3 4 5 6 7]
[ 6  8 10 12 14]
[[11 22 33]
 [14 25 36]]


Sum:  36
Minimum:  1
Maximum:  8
Mean:  8
Standard Deviation:  2.29128784747792
